---
- name: Copy New Image
  hosts: webservers
  gather_facts: False 
  remote_user: dlorenc
  tasks:
  - name: copy docker image
    command: gsutil cp gs://dockerize-builds/dockerize_{{ version }}.tar.gz .
  - name: docker load the image
    command: docker load -i dockerize_{{ version }}.tar.gz
    sudo: yes
  - name: delete the tar.gz
    command: rm dockerize_{{ version }}.tar.gz

- name: Deploy
  hosts: webservers
  serial: 1
  tasks:
  # Taking the server in and out of load balancing slows down the demo a bit.
  # This takes ~2 minutes with these in, and ~40s with them out.
  # - name: take the server out of load balancing
  #   shell: gcloud compute target-pools remove-instances webservers --instances {{ ansible_hostname }} --zone=us-central1-f
  #   delegate_to: 127.0.0.1

  - name: docker stop the old version
    shell: "docker stop $(docker ps | grep dockerize_ | awk '{ print $1 }')"
    sudo: yes
    ignore_errors: yes
  - name: docker run the new version
    command: docker run -d -p 80:8080 dockerize_{{ version }}
    sudo: yes

  # - name: add the server into load balancing
  #   shell: gcloud compute target-pools add-instances webservers --instances {{ ansible_hostname }} --zone=us-central1-f
  #   delegate_to: 127.0.0.1
